//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public string tconst { get; set; }
        public string typeTitle { get; set; }
        public string primaryTitle { get; set; }
        public string originalTitle { get; set; }
        public string startYear { get; set; }
        public string runtimeMinutes { get; set; }
        public string genres { get; set; }
    }
}
